### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by Talithaald** [Kanepu/Vortex-loader#2]
I have several questions about the web files, can i please get your discord? the invite link on the wiki expired. Thanks!

**Comment by Kanepu** [comment]
i am not the owner of the web files and i have very little to no experience with php so i would not be able to help you regarding that matter however if you still need help please comment here and ill provide my discord username

**Comment by Talithaald** [comment]
sorry for the late comment, yes sure i'd love to add your discord.

**Comment by Kanepu** [comment]
join [this server](https://discord.gg/UMVrs7c) and dm the bot

**Comment by Kanepu** [comment]
if i dont reply within 2 days you can start a new issue

**Comment by Talithaald** [comment]
going to be available in 8hours
